#!/bin/sh

# Copyright (C) 2006 OpenWrt.org
# 2011 Freifunk-KBU
# based on ntpclient's hotplug-script


check_interface_and_upload() {
        # $INTERFACE is passed from hotplug event
        [ "$INTERFACE" = "wan" ] || return
        /etc/tinc/upload_cert.sh &      
}
case "${ACTION:-ifup}" in
        ifup)
                check_interface_and_upload
        ;;
        ifdown)

        ;;
esac
